from path_configs import ROOT_PATH_GIT
from pathlib import Path

input_path = Path(ROOT_PATH_GIT) / 'proxies' /'old_proxies'
output_path = Path(ROOT_PATH_GIT) / 'results'

output_path = Path(ROOT_PATH_GIT)


country_map = {
    'JPN': 'JP',
    'NLD': 'NL',
    'CZE': 'CZ',
    'DEU': 'DE',
    'GRC': 'GR',
    'PRT': 'PT',
    'AUS': 'AU',
    'CHL': 'CL',
    'ITA': 'IT',
    'CAN': 'CA',
    'SVN': 'SI',
    'CHE': 'CH',
    'SVK': 'SK',
    'IRL': 'IE',
    'MEX': 'MX',
    'POL': 'PL',
    'BEL': 'BE',
    'SWE': 'SE',
    'ESP': 'ES',
    'EST': 'EE',
    'NOR': 'NO',
    'KOR': 'KR',
    'GBR': 'GB',
    'USA': 'US',
    'HUN': 'HU',
    'FIN': 'FI', 
    'AUT': 'AT',
    'LUX': 'LU',
    'FRA': 'FR',
    'RUS': 'RU',
    'NZL': 'NZ',
    'DNK': 'DK',
    'LVA': 'LV',
    'TUR': 'TR',
    'LTU': 'LT',
    'CRI': 'CR',
    'G7M': 'G7',
    'OECD': 'OECD',
    'AUS': 'AU',
    'CA': 'CA',
    'DNK': 'DK',
    'FRA': 'FR',
    'ISL': 'IS',
    'KOR': 'KR',
    'LUX': 'LU',
    'MEX': 'MX',
    'PRT': 'PT',
    'TUR': 'TR',
    'COL': 'CO',
    'EST': 'EE',
    'IND': 'IN',
    'IDN': 'ID',
    'ISR': 'IL',
    'SVN': 'SI'}