from path_configs import ROOT_PATH_GIT
from pathlib import Path

input_path = Path(ROOT_PATH_GIT) / 'proxies' /'old_proxies'
output_path = Path(ROOT_PATH_GIT) / 'results'

EU_countries = [
    "Belgium", "Bulgaria", "Czechia", "Denmark", "Germany", "Estonia", "Ireland",
    "Greece", "Spain", "France", "Croatia", "Italy", "Cyprus", "Latvia", "Lithuania",
    "Luxembourg", "Hungary", "Malta", "Netherlands", "Austria", "Poland", "Portugal",
    "Romania", "Slovenia", "Slovakia", "Finland", "Sweden", "Iceland", "Norway",
    "Switzerland", "United Kingdom", "Bosnia and Herzegovina", "North Macedonia",
    "Albania", "Serbia", "Turkey", "Kosovo"
]

EU_country_abbreviations = {
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CZ": "Czechia",
    "DK": "Denmark",
    "DE": "Germany",
    "EE": "Estonia",
    "IE": "Ireland",
    "EL": "Greece",
    "ES": "Spain",
    "FR": "France",
    "HR": "Croatia",
    "IT": "Italy",
    "CY": "Cyprus",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "HU": "Hungary",
    "MT": "Malta",
    "NL": "Netherlands",
    "AT": "Austria",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "FI": "Finland",
    "SE": "Sweden",
    "IS": "Iceland",
    "NO": "Norway",
    "CH": "Switzerland",
    "UK": "United Kingdom",
    "BA": "Bosnia and Herzegovina",
    "MK": "North Macedonia",
    "AL": "Albania",
    "RS": "Serbia",
    "TR": "Turkey",
    "XK": "Kosovo"
}

EU_country_full_name = {
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Germany": "DE",
    "Estonia": "EE",
    "Ireland": "IE",
    "Greece": "EL",
    "Spain": "ES",
    "France": "FR",
    "Croatia": "HR",
    "Italy": "IT",
    "Cyprus": "CY",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Hungary": "HU",
    "Malta": "MT",
    "Netherlands": "NL",
    "Austria": "AT",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "Slovenia": "SI",
    "Slovakia": "SK",
    "Finland": "FI",
    "Sweden": "SE",
    "Iceland": "IS",
    "Norway": "NO",
    "Switzerland": "CH",
    "United Kingdom": "UK",
    "Bosnia and Herzegovina": "BA",
    "North Macedonia": "MK",
    "Albania": "AL",
    "Serbia": "RS",
    "Turkey": "TR",
    "Kosovo": "XK"
}


country_map = {
    'JPN': 'JP',
    'NLD': 'NL',
    'CZE': 'CZ',
    'DEU': 'DE',
    'GRC': 'GR',
    'PRT': 'PT',
    'AUS': 'AU',
    'CHL': 'CL',
    'ITA': 'IT',
    'CAN': 'CA',
    'SVN': 'SI',
    'CHE': 'CH',
    'SVK': 'SK',
    'IRL': 'IE',
    'MEX': 'MX',
    'POL': 'PL',
    'BEL': 'BE',
    'SWE': 'SE',
    'ESP': 'ES',
    'EST': 'EE',
    'NOR': 'NO',
    'KOR': 'KR',
    'GBR': 'GB',
    'USA': 'US',
    'HUN': 'HU',
    'FIN': 'FI', 
    'AUT': 'AT',
    'LUX': 'LU',
    'FRA': 'FR',
    'RUS': 'RU',
    'NZL': 'NZ',
    'DNK': 'DK',
    'LVA': 'LV',
    'TUR': 'TR',
    'LTU': 'LT',
    'CRI': 'CR',
    'G7M': 'G7',
    'OECD': 'OECD',
    'AUS': 'AU',
    'CA': 'CA',
    'DNK': 'DK',
    'FRA': 'FR',
    'ISL': 'IS',
    'KOR': 'KR',
    'LUX': 'LU',
    'MEX': 'MX',
    'PRT': 'PT',
    'TUR': 'TR',
    'COL': 'CO',
    'EST': 'EE',
    'IND': 'IN',
    'IDN': 'ID',
    'ISR': 'IL',
    'SVN': 'SI'}
